/*
 * Hurl (https://hurl.dev)
 * Copyright (C) 2023 Orange
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *          http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
import { Movie } from "./movie";

/**
 * Our movie database.
 */
export const movies: Movie[] = [
    {
        id: 1,
        name: "Dune",
        artwork: "dune-800x1200.webp",
        director: "David Lynch",
        slug: "dune-1984",
        writers: ["David Lynch"],
        runningTimes: 137,
        releaseDate: new Date("1984-12-03"),
        actors: [
            "Kyle MacLachlan",
            "Jürgen Prochnow",
            "Max von Sydow",
            "Patrick Stewart",
            "Sting",
            "Sean Young",
        ],
        boxOffice: {
            min: 30900000,
            max: 37900000,
        },
        links: {
            wikipedia: "https://en.wikipedia.org/wiki/Dune_(1984_film)",
            imdb: "https://www.imdb.com/title/tt0087182/",
        },
    },
    {
        id: 2,
        name: "The Dark Crystal",
        artwork: "the-dark-crystal-800x1200.webp",
        director: "Jim Henson",
        slug: "the-dark-crystal",
        writers: ["David Odell", "Jim Henson"],
        runningTimes: 93,
        releaseDate: new Date("1982-12-17"),
        actors: [
            "Stephen Garlick",
            "Lisa Maxwell",
            "Billie Whitelaw",
            "Percy Edwards",
        ],
        boxOffice: {
            min: 41400000,
            max: 41400000,
        },
        links: {
            wikipedia: "https://en.wikipedia.org/wiki/The_Dark_Crystal",
            imdb: "https://www.imdb.com/title/tt0083791/",
        },
    },
    {
        id: 3,
        name: "Blade Runner",
        artwork: "blade-runner-800x1200.webp",
        director: "Ridley Scott",
        slug: "blade-runner",
        writers: ["Hampton Fancher", "David Peoples"],
        runningTimes: 117,
        releaseDate: new Date("1982-06-25"),
        actors: [
            "Harrison Ford",
            "Rutger Hauer",
            "Sean Young",
            "Edward James Olmos",
        ],
        boxOffice: {
            min: 41600000,
            max: 41600000,
        },
        links: {
            wikipedia: "https://en.wikipedia.org/wiki/Blade_Runner",
            imdb: "https://www.imdb.com/title/tt0083658/",
        },
    },
    {
        id: 4,
        name: "Tron",
        artwork: "tron-800x1200.webp",
        slug: "tron",
        director: "Steven Lisberger",
        writers: ["Steven Lisberger", "Bonnie MacBird", "Charles S. Haas"],
        runningTimes: 96,
        releaseDate: new Date("1982-07-09"),
        actors: [
            "Jeff Bridges",
            "Bruce Boxleitner",
            "David Warner",
            "Cindy Morgan",
            "Barnard Hughes",
        ],
        boxOffice: {
            min: 50000000,
            max: 50000000,
        },
        links: {
            wikipedia: "https://en.wikipedia.org/wiki/Tron",
            imdb: "https://www.imdb.com/title/tt0084827/",
        },
    },
    {
        id: 5,
        name: "Willow",
        artwork: "willow-800x1200.webp",
        director: "Ron Howard",
        slug: "willow",
        writers: ["Bob Dolman", "George Lucas"],
        runningTimes: 126,
        releaseDate: new Date("1988-05-20"),
        actors: [
            "Warwick Davis",
            "Val Kilmer",
            "Joanne Whalley",
            "Billy Barty",
            "Jean Marsh",
        ],
        boxOffice: {
            min: 137600000,
            max: 137600000,
        },
        links: {
            wikipedia: "https://en.wikipedia.org/wiki/Willow_(film)",
            imdb: "https://www.imdb.com/title/tt0096446/",
        },
    },
    {
        id: 6,
        name: "Conan the Barbarian",
        artwork: "conan-the-barbarian-800x1200.webp",
        slug: "conan-the-barbarian",
        director: "John Milius",
        writers: ["John Milius", "Oliver Stone"],
        runningTimes: 129,
        releaseDate: new Date("1982-05-14"),
        actors: [
            "Arnold Schwarzenegger",
            "James Earl Jones",
            "Sandahl Bergman",
            "Ben Davidson",
            "Cassandra Gaviola",
            "Gerry Lopez",
            "Mako",
            "Valerie Quennessen",
            "William Smith",
            "Max von Sydow",
        ],
        boxOffice: {
            min: 68900000,
            max: 79100000,
        },
        links: {
            wikipedia:
                "https://en.wikipedia.org/wiki/Conan_the_Barbarian_(1982_film)",
            imdb: "https://www.imdb.com/title/tt0082198/",
        },
    },
    {
        id: 7,
        name: "Indiana Jones and the Raiders of the Lost Ark",
        artwork: "raiders-of-the-lost-ark-800x1200.webp",
        director: "Steven Spielberg",
        slug: "raiders-of-the-lost-ark",
        writers: ["Lawrence Kasdan"],
        runningTimes: 115,
        releaseDate: new Date("1981-06-12"),
        actors: [
            "Harrison Ford",
            "Karen Allen",
            "Paul Freeman",
            "Ronald Lacey",
            "John Rhys-Davies",
            "Denholm Elliott",
        ],
        boxOffice: {
            min: 389900000,
            max: 389900000,
        },
        links: {
            wikipedia: "https://en.wikipedia.org/wiki/Raiders_of_the_Lost_Ark",
            imdb: "https://www.imdb.com/title/tt0082971/",
        },
    },
    {
        id: 8,
        name: "Top Gun",
        artwork: "top-gun-800x1200.webp",
        director: "Tony Scott",
        slug: "top-gun",
        writers: ["Jim Cash", "Jack Epps Jr."],
        runningTimes: 110,
        releaseDate: new Date("1986-05-12"),
        actors: [
            "Tom Cruise",
            "Kelly McGillis",
            "Val Kilmer",
            "Anthony Edwards",
            "Tom Skerritt",
        ],
        boxOffice: {
            min: 357300000,
            max: 357300000,
        },
        links: {
            wikipedia: "https://en.wikipedia.org/wiki/Top_Gun",
            imdb: "https://www.imdb.com/title/tt0092099/",
        },
    },
    {
        id: 9,
        name: "Aliens",
        artwork: "aliens-800x1200.webp",
        director: "James Cameron",
        slug: "aliens",
        writers: ["James Cameron", "David Giler", "Walter Hill"],
        runningTimes: 137,
        releaseDate: new Date("1986-07-18"),
        actors: ["Sigourney Weaver", "Michael Biehn", "Carrie Henn"],
        boxOffice: {
            min: 131000000,
            max: 183300000,
        },
        links: {
            wikipedia: "https://en.wikipedia.org/wiki/Aliens_(film)",
            imdb: "https://www.imdb.com/title/tt0090605",
        },
    },
    {
        id: 10,
        name: "Cocoon",
        artwork: "cocoon-800x1200.webp",
        director: "Ron Howard",
        slug: "cocoon",
        writers: ["Tom Benedek", "David Saperstein"],
        runningTimes: 117,
        releaseDate: new Date("1985-06-21"),
        actors: [
            "Don Ameche",
            "Wilford Brimley",
            "Hume Cronyn",
            "Brian Dennehy",
            "Jack Gilford",
            "Steve Guttenberg",
            "Maureen Stapleton",
            "Jessica Tandy",
            "Gwen Verdon",
            "Herta Ware",
            "Tahnee Welch",
        ],
        boxOffice: {
            min: 17500000,
            max: 85300000,
        },
        links: {
            wikipedia: "https://en.wikipedia.org/wiki/Cocoon_(film)",
            imdb: "https://www.imdb.com/title/tt0088933/",
        },
    },
    {
        id: 11,
        name: "Barry Lyndon",
        artwork: "barry-lyndon-800x1200.webp",
        director: "Stanley Kubrick",
        slug: "barry-lyndon",
        writers: ["Stanley Kubrick"],
        runningTimes: 187,
        releaseDate: new Date("1975-12-18"),
        actors: [
            "Ryan O'Neal",
            "Marisa Berenson",
            "Patrick Magee",
            "Hardy Kruger",
            "Diana Koerner",
            "Gay Hamilton",
        ],
        boxOffice: {
            min: 12000000,
            max: 20200000,
        },
        links: {
            wikipedia: "https://en.wikipedia.org/wiki/Barry_Lyndon",
            imdb: "https://www.imdb.com/title/tt0072684/",
        },
    },
    {
        id: 12,
        name: "Indiana Jones and the Temple of Doom",
        artwork: "indiana-jones-temple-of-doom-800x1200.webp",
        director: "Steven Spielberg",
        slug: "indiana-jones-and-the-temple-of-doom",
        writers: ["Willard Huyck", "Gloria Katz"],
        runningTimes: 118,
        releaseDate: new Date("1984-05-08"),
        actors: [
            "Harrison Ford",
            "Kate Capshaw",
            "Amrish Puri",
            "Roshan Seth",
            "Philip Stone",
            "Ke Huy Quan",
        ],
        boxOffice: {
            min: 333100000,
            max: 333100000,
        },
        links: {
            wikipedia:
                "https://en.wikipedia.org/wiki/Indiana_Jones_and_the_Temple_of_Doom",
            imdb: "https://www.imdb.com/title/tt0087469/",
        },
    },
    {
        id: 13,
        name: "Gremlins",
        artwork: "gremlins-800x1200.webp",
        director: "Joe Dante",
        slug: "gremlins",
        writers: ["Chris Columbus"],
        runningTimes: 106,
        releaseDate: new Date("1984-06-08"),
        actors: [
            "Zach Galligan",
            "Phoebe Cates",
            "Hoyt Axton",
            "Polly Holliday",
            "Frances Lee McCain",
        ],
        boxOffice: {
            min: 11000000,
            max: 212900000,
        },
        links: {
            wikipedia: "https://en.wikipedia.org/wiki/Gremlins",
            imdb: "https://www.imdb.com/title/tt0087363/",
        },
    },
    {
        id: 14,
        name: "Amadeus",
        artwork: "amadeus-800x1200.webp",
        director: "Miloš Forman",
        slug: "amadeus",
        writers: ["Peter Shaffer"],
        runningTimes: 161,
        releaseDate: new Date("1984-09-06"),
        actors: [
            "F. Murray Abraham",
            "Tom Hulce",
            "Elizabeth Berridge",
            "Simon Callow",
            "Roy Dotrice",
            "Christine Ebersole",
            "Jeffrey Jones",
            "Charles Kay",
        ],
        boxOffice: {
            min: 90000000,
            max: 90300000,
        },
        links: {
            wikipedia: "https://en.wikipedia.org/wiki/Amadeus_(film)",
            imdb: "https://www.imdb.com/title/tt0086879/",
        },
    },
    {
        id: 15,
        name: "Ghostbusters",
        artwork: "ghostbusters-800x1200.webp",
        director: "Ivan Reitman",
        slug: "ghostbusters",
        writers: ["Dan Aykroyd", "Harold Ramis"],
        runningTimes: 105,
        releaseDate: new Date("1984-06-08"),
        actors: [
            "Bill Murray",
            "Dan Aykroyd",
            "Sigourney Weaver",
            "Harold Ramis",
            "Rick Moranis",
        ],
        boxOffice: {
            min: 295200000,
            max: 295200000,
        },
        links: {
            wikipedia: "https://en.wikipedia.org/wiki/Ghostbusters",
            imdb: "https://www.imdb.com/title/tt0087332/",
        },
    },
    {
        id: 16,
        name: "Legend",
        artwork: "legend-800x1200.webp",
        director: "Ridley Scott",
        slug: "legend",
        writers: ["William Hjortsberg"],
        runningTimes: 89,
        releaseDate: new Date("1985-08-28"),
        actors: [
            "Tom Cruise",
            "Mia Sara",
            "Tim Curry",
            "David Bennent",
            "Alice Playten",
            "Billy Barty",
            "Cork Hubbert",
        ],
        boxOffice: {
            min: 23500000,
            max: 23500000,
        },
        links: {
            wikipedia: "https://en.wikipedia.org/wiki/Legend_(1985_film)",
            imdb: "https://www.imdb.com/title/tt0089469/",
        },
    },
    {
        id: 17,
        name: "Pale Rider",
        artwork: "pale-rider-800x1200.webp",
        director: "Clint Eastwood",
        slug: "pale-rider",
        writers: ["Michael Butler", "Dennis Shryack"],
        runningTimes: 116,
        releaseDate: new Date("1985-06-26"),
        actors: [
            "Clint Eastwood",
            "Michael Moriarty",
            "Carrie Snodgress",
            "Christopher Penn",
            "Richard Dysart",
            "Sydney Penny",
            "Richard Kiel",
            "Doug McGrath",
            "John Russell",
        ],
        boxOffice: {
            min: 41400000,
            max: 41400000,
        },
        links: {
            wikipedia: "https://en.wikipedia.org/wiki/Pale_Rider",
            imdb: "https://www.imdb.com/title/tt0089767/",
        },
    },
    {
        id: 18,
        name: "RoboCop",
        artwork: "robocop-800x1200.webp",
        director: "Paul Verhoeven",
        slug: "robocop",
        writers: ["Edward Neumeier", "Michael Miner"],
        runningTimes: 102,
        releaseDate: new Date("1987-07-17"),
        actors: [
            "Peter Weller",
            "Nancy Allen",
            "Daniel O'Herlihy",
            "Ronny Cox",
            "Kurtwood Smith",
            "Miguel Ferrer",
        ],
        boxOffice: {
            min: 53400000,
            max: 53400000,
        },
        links: {
            wikipedia: "https://en.wikipedia.org/wiki/RoboCop",
            imdb: "https://www.imdb.com/title/tt0093870/",
        },
    },
    {
        id: 19,
        name: "Scarface",
        artwork: "scarface-800x1200.webp",
        director: "Brian De Palma",
        slug: "scarface",
        writers: ["Oliver Stone"],
        runningTimes: 170,
        releaseDate: new Date("1983-12-01"),
        actors: ["Al Pacino"],
        boxOffice: {
            min: 66000000,
            max: 66000000,
        },
        links: {
            wikipedia: "https://en.wikipedia.org/wiki/Scarface_(1983_film)",
            imdb: "https://www.imdb.com/title/tt0086250/",
        },
    },
    {
        id: 20,
        name: "The Terminator",
        artwork: "the-terminator-800x1200.webp",
        director: "James Cameron",
        slug: "the-terminator",
        writers: ["James Cameron", "Gale Anne Hurd"],
        runningTimes: 107,
        releaseDate: new Date("1984-10-26"),
        actors: [
            "Arnold Schwarzenegger",
            "Michael Biehn",
            "Linda Hamilton",
            "Paul Winfield",
        ],
        boxOffice: {
            min: 78300000,
            max: 78300000,
        },
        links: {
            wikipedia: "https://en.wikipedia.org/wiki/The_Terminator",
            imdb: "https://www.imdb.com/title/tt0088247/",
        },
    },
    {
        id: 21,
        name: "The Thing",
        artwork: "the-thing-800x1200.webp",
        director: "John Carpenter",
        slug: "the-thing",
        writers: ["Bill Lancaster"],
        runningTimes: 109,
        releaseDate: new Date("1982-06-25"),
        actors: ["Kurt Russell"],
        boxOffice: {
            min: 19600000,
            max: 19600000,
        },
        links: {
            wikipedia: "https://en.wikipedia.org/wiki/The_Thing_(1982_film)",
            imdb: "https://www.imdb.com/title/tt0084787/",
        },
    },
    {
        id: 22,
        name: "Excalibur",
        artwork: "excalibur-800x1200.webp",
        director: "John Boorman",
        slug: "excalibur",
        writers: ["Rospo Pallenberg", "John Boorman"],
        runningTimes: 141,
        releaseDate: new Date("1981-04-10"),
        actors: [
            "Nigel Terry",
            "Helen Mirren",
            "Nicholas Clay",
            "Cherie Lunghi",
            "Paul Geoffrey",
            "Nicol Williamson",
        ],
        boxOffice: {
            min: 11000000,
            max: 35000000,
        },
        links: {
            wikipedia: "https://en.wikipedia.org/wiki/Excalibur_(film)",
            imdb: "https://www.imdb.com/title/tt0082348/",
        },
    },
];
